// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AUDIT_LOG", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EVENT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EVENT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Final Universitaria de Software",
                            Status = "Active",
                            Venue = "Auditorio UNAJ"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RESERVATION", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("RESERVATION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SEAT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("SEAT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 1,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 2,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 3,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 4,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 5,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 6,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 7,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 8,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 9,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 10,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 11,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 12,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 13,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 14,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 15,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 16,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 17,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 18,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 19,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 20,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 21,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 22,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 23,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 24,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 25,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 26,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 27,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 28,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 29,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 30,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 31,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 32,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 33,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 34,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 35,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 36,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 37,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 38,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 39,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 40,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 41,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 42,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 43,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 44,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 45,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 46,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 47,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 48,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 49,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 50,
                            SectorId = 1,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 51,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 52,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000053"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 53,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000054"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 54,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000055"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 55,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000056"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 56,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000057"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 57,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000058"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 58,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000059"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 59,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000060"),
                            RowIdentifier = "Fila 1",
                            SeatNumber = 60,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000061"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 61,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000062"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 62,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000063"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 63,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000064"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 64,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000065"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 65,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000066"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 66,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000067"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 67,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000068"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 68,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000069"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 69,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000070"),
                            RowIdentifier = "Fila 2",
                            SeatNumber = 70,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000071"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 71,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000072"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 72,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000073"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 73,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000074"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 74,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000075"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 75,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000076"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 76,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000077"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 77,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000078"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 78,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000079"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 79,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000080"),
                            RowIdentifier = "Fila 3",
                            SeatNumber = 80,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000081"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 81,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000082"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 82,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000083"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 83,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000084"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 84,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000085"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 85,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000086"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 86,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000087"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 87,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000088"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 88,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000089"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 89,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000090"),
                            RowIdentifier = "Fila 4",
                            SeatNumber = 90,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000091"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 91,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000092"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 92,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000093"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 93,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000094"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 94,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000095"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 95,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000096"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 96,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000097"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 97,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000098"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 98,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000099"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 99,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000100"),
                            RowIdentifier = "Fila 5",
                            SeatNumber = 100,
                            SectorId = 2,
                            Status = "Available",
                            Version = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.SECTOR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("SECTOR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            EventId = 1,
                            Name = "VIP",
                            Price = 25000.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            EventId = 1,
                            Name = "Preferencial",
                            Price = 12500.00m
                        });
                });

            modelBuilder.Entity("Domain.Entities.USER", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AUDIT_LOG", b =>
                {
                    b.HasOne("Domain.Entities.USER", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RESERVATION", b =>
                {
                    b.HasOne("Domain.Entities.SEAT", "Seat")
                        .WithMany("Reservations")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.USER", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.SEAT", b =>
                {
                    b.HasOne("Domain.Entities.SECTOR", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Domain.Entities.SECTOR", b =>
                {
                    b.HasOne("Domain.Entities.EVENT", "Event")
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Domain.Entities.EVENT", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("Domain.Entities.SEAT", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Domain.Entities.SECTOR", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Domain.Entities.USER", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
